
spring:
  application: name=auth-service
  mongodb:
    uri: ${MONGODB_URI:mongodb+srv://singhv:NotANewPasswordForMongo@cluster0.akdsgeh.mongodb.net/carsharingDB?retryWrites=true&w=majority&appName=Cluster0}
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${PORT:8081}
    statusPageUrl: http://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}/actuator/health
    homePageUrl: http://${eureka.instance.hostname}/

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}