server:
  port: 8082

spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/carsharing_vehicles}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info