server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**
          filters:
            - StripPrefix=0
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/ride/**,/api/myrides/**
          filters:
            - StripPrefix=0
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway