spring.application.name=CarSharingTZ
GOOGLE_API_KEY=your_google_api_key_here
firebase.config.path=classpath:firebaseSdk/firebase-sdk-sample.json
firebase.database.url=your_firebase_database_url_here
spring.data.mongodb.uri=mongodb+srv://username:password@your-cluster-address/database
spring.data.mongodb.database=your_database_name
spring.data.mongodb.options.retryWrites=false
minDistanceInMetersBetween2PickupPoints=1200
spring.cloud.gcp.core.enabled=false
spring.cloud.gcp.firestore.enabled=false
server.port=8911
# Rest of your properties...