package com.singhv.tripservice.model;

import com.singhv.common.models.Points;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.Date;

/**
 * Rides collection - tracks passenger bookings
 */
@Document(collection = "rides")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Rides {

    @Id
    private String rideId;  // Auto-generated by MongoDB

    private String passengerId;  // userId from frontend
    private String tripId;
    private String driverId;

    private Points pickupLocation;
    private Points dropoffLocation;

    private int requestedSeats;
    private String rideStatus;  // REQUESTED, CONFIRMED, COMPLETED, CANCELLED

    private Instant rideStartTimeUTC;  // Store in UTC
    private String rideTimezone;  // Original timezone

    private Date createdAt;
    private Date updatedAt;
}
