server:
  port: 8084

spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/carsharing_rides}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

google:
  maps:
    api-key: ${GOOGLE_API_KEY:your-google-maps-api-key}

minDistanceInMetersBetween2PickupPoints: 500