server:
  port: ${PORT:8084}

spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/carsharing_rides}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${PORT:8084}
    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/

management:
  endpoints:
    web:
      exposure:
        include: health,info

google:
  maps:
    api-key: ${GOOGLE_API_KEY:your-google-maps-api-key}

minDistanceInMetersBetween2PickupPoints: 500